In [1]:
import pandas as pd
import plotly.graph_objects as go

In [2]:
ma_test_res = pd.read_pickle("ma_test_res.pkl")
all_trades = pd.read_pickle("all_trades.pkl")

In [3]:
all_trades.shape

(65842, 11)

In [4]:
ma_test_res.shape

(630, 8)

In [5]:
ma_test_res.head()

,pair,num_trades,total_gain,mean_gain,min_gain,max_gain,mashort,malong
0,GBP_USD,555,173.3,0.312252,-128.0,165.2,4,8
1,GBP_USD,302,201.4,0.666887,-92.6,196.4,4,16
2,GBP_USD,274,-139.3,-0.508394,-100.9,194.0,8,16
3,GBP_USD,200,-112.9,-0.564500,-106.8,188.2,4,32
4,GBP_USD,154,-597.8,-3.881818,-141.4,184.5,8,32

In [6]:
ma_test_res.columns

Index(['pair', 'num_trades', 'total_gain', 'mean_gain', 'min_gain', 'max_gain',
       'mashort', 'malong'],
      dtype='str')

In [7]:
ma_test_res = ma_test_res[['pair', 'num_trades', 'total_gain','mashort', 'malong']]

In [8]:
ma_test_res["CROSS"] = "MA_" + ma_test_res.mashort.map(str) + "_" + ma_test_res.malong.map(str)

In [9]:
df_all_gains = ma_test_res.groupby(by=["CROSS", "mashort", "malong"], as_index=False).sum()

In [10]:
df_all_gains.sort_values(by="total_gain", ascending=False, inplace=True)

In [11]:
df_all_gains.head()

,CROSS,mashort,malong,pair,num_trades,total_gain
19,MA_4_8,4,8,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,11700,8846.2
25,MA_8_16,8,16,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,5751,5364.0
15,MA_4_16,4,16,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,6501,4618.1
21,MA_64_128,64,128,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,684,3834.5
23,MA_64_96,64,96,GBP_USDGBP_CADGBP_JPYGBP_NZDGBP_CHFEUR_GBPEUR_...,1021,2061.1

In [12]:
ma_8_16 = ma_test_res[ma_test_res.CROSS=='MA_8_16'].copy()

In [13]:
ma_8_16.sort_values(by="total_gain", ascending=False, inplace=True)

In [14]:
total_p = len(ma_8_16.pair.unique())

In [15]:
ma_8_16[ma_8_16.total_gain>0].shape[0]

14

In [16]:
14 / total_p

0.6666666666666666

In [17]:


for cross in df_all_gains.CROSS.unique():
    df_temp = ma_test_res[ma_test_res.CROSS==cross]
    total_p = df_temp.shape[0]
    n_good = df_temp[df_temp.total_gain>0].shape[0]
    print(f"{cross:12} {n_good:4} {(n_good/total_p)*100:4.0f}%")

MA_4_8         16   76%
MA_8_16        14   67%
MA_4_16        15   71%
MA_64_128      10   48%
MA_64_96       10   48%
MA_4_32        12   57%
MA_32_128      10   48%
MA_4_128        9   43%
MA_8_128        8   38%
MA_4_256        6   29%
MA_8_32         5   24%
MA_64_256       6   29%
MA_4_96         5   24%
MA_32_256       7   33%
MA_32_96        4   19%
MA_24_128       5   24%
MA_24_256       7   33%
MA_4_64         4   19%
MA_8_256        6   29%
MA_16_128       4   19%
MA_16_32        3   14%
MA_16_256       6   29%
MA_24_96        6   29%
MA_8_64         4   19%
MA_8_96         5   24%
MA_16_96        3   14%
MA_32_64        2   10%
MA_16_64        2   10%
MA_24_64        2   10%
MA_24_32        0    0%

In [18]:
crosses = df_all_gains.CROSS.unique()[:3]

In [19]:
crosses

<StringArray>
['MA_4_8', 'MA_8_16', 'MA_4_16']
Length: 3, dtype: str

In [20]:
ma_test_res.head(2)

      pair  num_trades  total_gain  mashort  malong    CROSS
0  GBP_USD         555       173.3        4       8   MA_4_8
1  GBP_USD         302       201.4        4      16  MA_4_16

In [21]:
df_good = ma_test_res[(ma_test_res.CROSS.isin(crosses)) & (ma_test_res.total_gain>0)].copy()

In [22]:
df_good.head(2)

      pair  num_trades  total_gain  mashort  malong    CROSS
0  GBP_USD         555       173.3        4       8   MA_4_8
1  GBP_USD         302       201.4        4      16  MA_4_16

In [23]:
our_pairs = list(df_good.pair.value_counts()[:9].index)

In [24]:
our_pairs

['GBP_CAD',
 'GBP_JPY',
 'EUR_JPY',
 'USD_CAD',
 'USD_JPY',
 'USD_CHF',
 'NZD_USD',
 'NZD_CAD',
 'NZD_CHF']

In [25]:
all_trades.head(2)

,time,mid_c,DIFF,DIFF_PREV,IS_TRADE,DELTA,GAIN,PAIR,MASHORT,MALONG,DURATION
9,2026-02-27 08:00:00+00:00,1.34960,-0.000115,0.000012,-1,-14.8,14.8,GBP_USD,4,8,11.0
20,2026-02-27 19:00:00+00:00,1.34812,0.000736,-0.000016,1,-75.7,-75.7,GBP_USD,4,8,52.0

In [26]:
all_trades["CROSS"] = "MA_" + all_trades.MASHORT.map(str) + "_" + all_trades.MALONG.map(str)

In [27]:
trades_cad_jpy = all_trades[(all_trades.CROSS=="MA_8_16") & (all_trades.PAIR=="CAD_JPY")].copy()

In [28]:
trades_cad_jpy.head()

,time,mid_c,DIFF,DIFF_PREV,IS_TRADE,DELTA,GAIN,PAIR,MASHORT,MALONG,DURATION,CROSS
47,2026-03-02 22:00:00+00:00,115.088,-0.007750,0.016812,-1,-1.6,1.6,CAD_JPY,8,16,3.0,MA_8_16
50,2026-03-03 01:00:00+00:00,115.072,0.015563,-0.008312,1,4.7,4.7,CAD_JPY,8,16,9.0,MA_8_16
59,2026-03-03 10:00:00+00:00,115.119,-0.002625,0.007062,-1,29.3,-29.3,CAD_JPY,8,16,6.0,MA_8_16
65,2026-03-03 16:00:00+00:00,115.412,0.030250,-0.006313,1,-34.9,-34.9,CAD_JPY,8,16,11.0,MA_8_16
76,2026-03-04 03:00:00+00:00,115.063,-0.010937,0.022750,-1,0.8,-0.8,CAD_JPY,8,16,20.0,MA_8_16

In [29]:
trades_cad_jpy['CUM_GAIN'] = trades_cad_jpy.GAIN.cumsum()

In [30]:
def plot_line(df_plot, name):
    fig = go.Figure()
    fig.add_trace(go.Scatter( 
        x=df_plot.time,
        y=df_plot.CUM_GAIN,
        line=dict(width=2,color="#3d825f"),
        line_shape='spline',
        name=name,
        mode='lines'
        ))
    fig.update_layout(width=1000,height=400,
        margin=dict(l=15,r=15,b=10),
        font=dict(size=10,color="#e1e1e1"),
        paper_bgcolor="#1e1e1e",
        plot_bgcolor="#1e1e1e",
        title=name)
    fig.update_xaxes(
        linewidth=1,
        linecolor='#3a4a54',
        showgrid=False,
        zeroline=False
    )
    fig.update_yaxes(
        linewidth=1,
        linecolor='#3a4a54',
        showgrid=False,
        zeroline=False
    )
    fig.show()

In [31]:
plot_line(trades_cad_jpy, "CAD_JPY")

In [32]:
c = 'MA_8_16'
for p in our_pairs:
    temp_df = all_trades[(all_trades.CROSS==c)&(all_trades.PAIR==p)].copy()
    temp_df['CUM_GAIN'] = temp_df.GAIN.cumsum()
    plot_line(temp_df, p + "_" + c)

In [33]:
for c in crosses:   
    temp_df = all_trades[(all_trades.CROSS==c)].copy()    
    temp_df = temp_df.groupby(by="time", as_index=False).sum()
    temp_df['CUM_GAIN'] = temp_df.GAIN.cumsum()
    plot_line(temp_df, c)